### ISSUE TITLE
RubyGems version is 0.1.0, master branch is newer

### ISSUE THREAD

**Issue by sebbean** [tpitale/staccato-rails#17]
Just ran into an error using the rubygems version of the gem
```
NoMethodError (undefined method `merge' for nil:NilClass):
staccato-rails (0.1.0) lib/staccato/subscribers/timing.rb:33:in `track!'
```

But it looks like there's a fix on master
https://github.com/tpitale/staccato-rails/blob/78f9a488f385ee8cf58c32858c7f75987a8f9e39/lib/staccato/subscribers/timing.rb#L33-L33

note line 33 'merge' isnt on master (it's line 35)

Hoping this fixes my exception on prod.

**Comment by sebbean** [comment]
FWIW updating to github master's version did not fix the exception - merely moved the line down to :35

```
NoMethodError (undefined method `merge' for nil:NilClass):  
staccato-rails (78f9a488f385) lib/staccato/subscribers/timing.rb:35:in `track!'
staccato-rails (78f9a488f385) lib/staccato/subscribers/timing.rb:5:in `call'
```

manually disabling timing tracking now
https://github.com/tpitale/staccato-rails/blob/78f9a488f385ee8cf58c32858c7f75987a8f9e39/README.md#L78-L83

**Comment by epugh** [comment]
is sthis still an open issue?   Was looking at this to replace my use of `gabba`...
