### ISSUE TITLE
Timing error: "undefined method `timing' for nil:NilClass"

### ISSUE THREAD

**Issue by jtomaszewski** [tpitale/staccato-rails#5]
What happened:
I just installed and configured the plugin, but `Staccato::Subscribers::Timing` raises an error.

This method returns nil:
```rb
     def tracker
        @tracker ||= payload['staccato.tracker']
      end
```

My setup:
- rails 4.2

Logs:
```
00:37:51 web.1   | NoMethodError - undefined method `timing' for nil:NilClass:
00:37:51 web.1   |    () opt/boxen/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/staccato-rails-13ad70d63b4b/lib/staccato/subscribers/timing.rb:25:in `track!'
00:37:51 web.1   |    () opt/boxen/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/staccato-rails-13ad70d63b4b/lib/staccato/subscribers/timing.rb:5:in `call'
00:37:51 web.1   |   activesupport (4.2.0) lib/active_support/notifications/fanout.rb:127:in `finish'
00:37:51 web.1   |   activesupport (4.2.0) lib/active_support/notifications/fanout.rb:46:in `block in finish'
00:37:51 web.1   |   activesupport (4.2.0) lib/active_support/notifications/fanout.rb:46:in `finish'
00:37:51 web.1   |   activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:36:in `finish'
00:37:51 web.1   |   activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:25:in `ensure in instrument'
00:37:51 web.1   |   activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:25:in `instrument'
00:37:51 web.1   |   activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
00:37:51 web.1   |   actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
```

**Comment by jtomaszewski** [comment]
I had my staccato configuration in `config/initializers/staccato.rb` and thus staccato-rails ignored my staccato config, which were still empty at the phase of binding Timing subscriber.

https://github.com/tpitale/staccato-rails/pull/6 fixes it.

**Comment by tpitale** [comment]
When is the error raised? On a request … or on startup?

**Comment by jtomaszewski** [comment]
On every request [at least in development environment].

**Comment by tpitale** [comment]
Usage: https://github.com/tpitale/staccato-rails#usage

Please place configuration in the environment files as required.
